version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:862547479026:task-definition/TaskApp:9"
        LoadBalancerInfo:
          ContainerName: "task"
          ContainerPort: 5004